name: CI/CD - Smart Network Analyzer

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/smart-network-backend ./backend

      - name: Build Frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/smart-network-frontend ./frontend

      - name: Push Backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/smart-network-backend

      - name: Push Frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/smart-network-frontend
